import pandera as pa
import pandas as pd


schema = pa.DataFrameSchema({
    "Summary": pa.Column(str, coerce=True, required=False, nullable=True),
    "Issue key": pa.Column(str, coerce=True, required=False, nullable=True),
    "Issue id": pa.Column(str, coerce=True, required=True, nullable=False),
    "Issue Type": pa.Column(str, coerce=True, required=False, nullable=True),
    "Status": pa.Column(str, coerce=True, required=False, nullable=True),
    "Project key": pa.Column(str, coerce=True, required=False, nullable=True),
    "Project name": pa.Column(str, coerce=True, required=False, nullable=True),
    "Project type": pa.Column(str, coerce=True, required=False, nullable=True),
    "Project lead": pa.Column(str, coerce=True, required=False, nullable=True),
    "Project description": pa.Column(str, coerce=True, required=False, nullable=True),
    "Project url": pa.Column(str, coerce=True, required=False, nullable=True),
    "Priority": pa.Column(str, coerce=True, required=False, nullable=True),
    "Resolution": pa.Column(str, coerce=True, required=False, nullable=True),
    "Assignee": pa.Column(str, coerce=True, required=False, nullable=True),
    "Reporter": pa.Column(str, coerce=True, required=False, nullable=True),
    "Creator": pa.Column(str, coerce=True, required=False, nullable=True),
    "Created": pa.Column(pd.DatetimeTZDtype(tz='Asia/Hong_Kong'), coerce=True, required=False, nullable=True),
    "Updated": pa.Column(pd.DatetimeTZDtype(tz='Asia/Hong_Kong'), coerce=True, required=False, nullable=True),
    "Last Viewed": pa.Column(pd.DatetimeTZDtype(tz='Asia/Hong_Kong'), coerce=True, required=False, nullable=True),
    "Resolved": pa.Column(str, coerce=True, required=False, nullable=True),
    "Due Date": pa.Column(pd.DatetimeTZDtype(tz='Asia/Hong_Kong'), coerce=True, required=False, nullable=True),
    "Description": pa.Column(str, coerce=True, required=False, nullable=True),
    "Environment": pa.Column(str, coerce=True, required=False, nullable=True),
    "Original Estimate": pa.Column(str, coerce=True, required=False, nullable=True),
    "Remaining Estimate": pa.Column(str, coerce=True, required=False, nullable=True),
    "Time Spent": pa.Column(float, coerce=True, required=False, nullable=True),
    "Work Ratio": pa.Column(float, coerce=True, required=False, nullable=True),
    "Σ Original Estimate": pa.Column(float, coerce=True, required=False, nullable=True),
    "Σ Remaining Estimate": pa.Column(float, coerce=True, required=False, nullable=True),
    "Σ Time Spent": pa.Column(float, coerce=True, required=False, nullable=True),
    "Security Level": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (Account Number)": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (Account Type)": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (Address 1)": pa.Column(str, coerce=True, required=False, nullable=True),
    "Custom field (Address 2)": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (Address Book)": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (Air Conditioners)": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (Air Coolers)": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (Air Purifiers)": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (Approval Date)": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (Approval Status)": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (Area)": pa.Column(str, coerce=True, required=False, nullable=True),
    "Custom field (BR Certificate Number)": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (BR Certificate Validity)": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (BR Expired)": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (Block)": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (CD Players)": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (COVID19 Clarification)": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (CRN)": pa.Column(int, coerce=True, required=False, nullable=True),
    "Custom field (CRN price - Air Conditioners)": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (CRN price - CRT TVs)": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (CRN price - Computers)": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (CRN price - LCD TVs)": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (CRN price - Monitors)": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (CRN price - Printers)": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (CRN price - Refrigerators)": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (CRN price - Scanners)": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (CRN price - Washing Machines)": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (Cancel Reason by Customer)": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (Cancel Reason by Internal)": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (Car Park Space Available)": pa.Column(str, coerce=True, required=False, nullable=True),
    "Custom field (Case Number)": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (Cassette Players)": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (Category)": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (Channel)": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (Collected Date)": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (Collected Date Time)": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (Collection Category)": pa.Column(str, coerce=True, required=False, nullable=True),
    "Custom field (Company Name)": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (Complaint Category)": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (Completed Date)": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (Completed Date Time)": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (Computers)": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (Confirmed Date Time)": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (Contract Expired)": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (Contract Expiry Date)": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (Contract ID)": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (Created Date)": pa.Column(pd.DatetimeTZDtype(tz='Asia/Hong_Kong'), coerce=True, required=False, nullable=True),
    "Custom field (Created Time)": pa.Column(str, coerce=True, required=False, nullable=True),
    "Custom field (Customer Confirmation Date)": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (Customer Confirmation Time)": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (Customer Email)": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (Customer First Name)": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (Customer ID)": pa.Column(int, coerce=True, required=False, nullable=True),
    "Custom field (Customer Phone (Primary))": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (Customer Phone (Secondary))": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (Customer Surname)": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (Customer Type)": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (DDN price - Air Conditioners)": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (DDN price - CRT TVs)": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (DDN price - Computers)": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (DDN price - LCD TVs)": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (DDN price - Monitors)": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (DDN price - Printers)": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (DDN price - Refrigerators)": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (DDN price - Scanners)": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (DDN price - Washing Machines)": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (DVD Players)": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (Date Time to be Confirmed)": pa.Column(str, coerce=True, required=False, nullable=True),
    "Custom field (Dehumidifiers)": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (Delivered Date)": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (Delivered Date Time)": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (Desk Lamps)": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (Difficult Access)": pa.Column(str, coerce=True, required=False, nullable=True),
    "Custom field (District)": pa.Column(str, coerce=True, required=False, nullable=True),
    "Custom field (Driver ID)": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (Driver Name)": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (Duplicated from)": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (E&C Serial Number)": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (Electric Hot Pots)": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (Electric Kettles)": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (Elevator Available)": pa.Column(str, coerce=True, required=False, nullable=True),
    "Custom field (Email)": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (Email Address of Account)": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (Enquiry Category)": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (Epic Colour)": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (Epic Link)": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (Epic Name)": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (Epic Status)": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (Expiry Date)": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (Fans)": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (Fax Machines)": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (First Name)": pa.Column(str, coerce=True, required=False, nullable=True),
    "Custom field (Floor)": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (Hair Dryers)": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (Heaters)": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (Induction Cookers)": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (Input Manually By User)": pa.Column(str, coerce=True, required=False, nullable=True),
    "Custom field (Irons)": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (Juicers)": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (Master Account)": pa.Column(str, coerce=True, required=False, nullable=True),
    "Custom field (Message)": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (Microwaves)": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (Mixers)": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (Mobile Phones)": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (Monitors)": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (Need Follow)": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (No Room / Floor Info)": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (Order Channel)": pa.Column(str, coerce=True, required=False, nullable=True),
    "Custom field (Other Customer Type)": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (Other Source Category)": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (Other Where did you hear from us)": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (Others)": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (Others Dsc. Txt.)": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (Others Non-WEEE Remarks)": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (Ovens)": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (Parent Company BR Number)": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (Pending Day)": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (Phone (Primary))": pa.Column(str, coerce=True, required=False, nullable=True),
    "Custom field (Phone (Secondary))": pa.Column(str, coerce=True, required=False, nullable=True),
    "Custom field (Phone of Account)": pa.Column(int, coerce=True, required=False, nullable=True),
    "Custom field (Preferred Collection Date)": pa.Column(pd.DatetimeTZDtype(tz='Asia/Hong_Kong'), coerce=True, required=False, nullable=True),
    "Custom field (Preferred Collection Time)": pa.Column(str, coerce=True, required=False, nullable=True),
    "Custom field (Previous Reschedule Reason)": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (Printers)": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (Rank)": pa.Column(str, coerce=True, required=False, nullable=True),
    "Custom field (Received By)": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (Received Date)": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (Refrigerators)": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (Region)": pa.Column(str, coerce=True, required=False, nullable=True),
    "Custom field (Reject Reason)": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (Related Tx)": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (Remarks)": pa.Column(str, coerce=True, required=False, nullable=True),
    "Custom field (Requested Date Time)": pa.Column(str, coerce=True, required=False, nullable=True),
    "Custom field (Reschedule Reason)": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (Reschedule To)": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (Rescheduled From)": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (Rice Cookers)": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (Room)": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (Sales Order Number (Retail Only))": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (Scanners)": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (Scheduled Date)": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (Scheduled Date Time)": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (Search Account Number)": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (Source Category)": pa.Column(str, coerce=True, required=False, nullable=True),
    "Custom field (Story Points)": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (Surname)": pa.Column(str, coerce=True, required=False, nullable=True),
    "Custom field (TVs with screen not less than 30' - CRT)": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (TVs with screen not less than 30' - LCD)": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (TVs with screen up to 30' - CRT)": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (TVs with screen up to 30' - LCD)": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (Telephones)": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (Title)": pa.Column(str, coerce=True, required=False, nullable=True),
    "Custom field (Toasters)": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (Type)": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (Vacuum Cleaners)": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (Washing Machines)": pa.Column(float, coerce=True, required=False, nullable=True),
    "Custom field (Where did you hear from us?)": pa.Column(float, coerce=True, required=False, nullable=True),
})